### ISSUE TITLE
您好 我有1个小米mini usb黄色无线网卡 无法识别模式，可以扫到信号。

### ISSUE THREAD

**Issue by ilovebamboo** [msylgj/R2S-R4S-OpenWrt#3]
如何驱动？
![image](https://user-images.githubusercontent.com/6214084/103495300-4757ab00-4e75-11eb-846f-9789cbd2f0e8.png)
![image](https://user-images.githubusercontent.com/6214084/103495313-5179a980-4e75-11eb-8024-f2858ccbf725.png)
![image](https://user-images.githubusercontent.com/6214084/103495333-67876a00-4e75-11eb-9530-b798793417cd.png)
已经开启，删除重新添加 重启都是无法扫描到openwrt 无线型号，请问有办法解决吗？

**Comment by msylgj** [comment]
这一版固件没用加入任何无线网卡支持，需要用无线的话只能换固件
