### ISSUE TITLE
有电报群吗

### ISSUE THREAD

**Issue by topsite** [msylgj/R2S-R4S-OpenWrt#5]
也希望增加x86版本

**Comment by msylgj** [comment]
没有单独的，可以加入immortalWrt的电报群。
x86只需要改config里面的target和autocore插件就可以了

**Comment by topsite** [comment]
> 没有单独的，可以加入immortalWrt的电报群。 x86只需要改config里面的target和autocore插件就可以了

r4s 5.15内核的刷好，openclash上传配置yaml提示格式错误，同配置用在5.4内核上就没问题。好像是什么ali什么错误

**Comment by msylgj** [comment]
> > 没有单独的，可以加入immortalWrt的电报群。 x86只需要改config里面的target和autocore插件就可以了
> 
> r4s 5.15内核的刷好，openclash上传配置yaml提示格式错误，同配置用在5.4内核上就没问题。好像是什么ali什么错误

master分支和2102分支用的yaml版本不一样，格式要求严格一些，具体要看日志
