### ISSUE TITLE
诚心请教如何R2S添加hello world

### ISSUE THREAD

**Issue by super27035** [msylgj/R2S-R4S-OpenWrt#7]
首先感谢你的分享，学习了很多，我发现用你的脚本编译r2s比lede的脚本开机启动速度快多了，很棒，但是我一直试了好多方法想把 hello world编译进去，就是不成功，所以过来请教大佬。

我在我的prepare_package.sh里面添加

# Add Hello World #
# 完整克隆 lua-maxminddb 仓库
git clone https://github.com/jerrykuku/lua-maxminddb.git feeds/luci/applications/lua-maxminddb
# 完整克隆 luci-app-vssr 仓库
git clone https://github.com/super27035/luci-app-vssr.git feeds/luci/applications/luci-app-vssr

在config里面也相应添加
### Hello World ###
CONFIG_PACKAGE_luci-app-vssr=y  # 添加 Hello World
CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray=y
CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Trojan=y
CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Kcptun=y
CONFIG_PACKAGE_luci-app-vssr_INCLUDE_Xray_plugin=y
CONFIG_PACKAGE_luci-app-vssr_INCLUDE_ShadowsocksR_Server=y

但编译就是不成功，不知道问题出在哪里，
我用同样的方法在lede的库就可以编译出来，但用Immortalwrt却不行，

如大佬有任何建议，我都想尝试一下，在此先感谢！！

**Comment by msylgj** [comment]
make defconfig之后检查一下.config里面是否有CONFIG_PACKAGE_luci-app-vssr，如果没有的话你可能需要
`ln -sf ../../../feeds/luci/applications/luci-app-xxx ./package/feeds/luci/luci-app-xxxx`

**Comment by super27035** [comment]
感谢你回复的谢谢，我早上立即试了一下，确实加上去你建议的命令就可以编译成功了，再次感谢！
